In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
def getInfo(df):
  no_of_cols=df.shape[1]
  inform=[[[]for j in range(5)] for i in range(no_of_cols)]

  attrs=[i for i in df]
  lenght=len(df[attrs[0]])
  for i in range(0,no_of_cols):
    #print(i)
    inform[i][0]=attrs[i]
    inform[i][1]=df[attrs[i]].dtypes
    inform[i][2]=lenght
    inform[i][3]=len(df[attrs[i]].unique())
    inform[i][4]=df[attrs[i]].isna().sum()
    


  inform = pd.DataFrame(inform,columns=['ATTRIBUTE', 'TYPE','VALUES','UNIQUE', 'NANS' ])

  return inform

In [ ]:
uncleaned_df=pd.read_csv("/content/gdrive/MyDrive/capstone project/datasets/tweets/tweets_2.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (4,5,6,7,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [ ]:
uncleaned_df.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,DeSota Wilson,"Atlanta, GA","Biz Consultant, real estate, fintech, startups...",2009-04-26 20:05:09,8534.0,7605,4838,False,2021-02-10 23:59:04,Blue Ridge Bank shares halted by NYSE after #b...,['bitcoin'],Twitter Web App,False
1,CryptoND,NaN,ðŸ˜Ž BITCOINLIVE is a Dutch platform aimed at inf...,2019-10-17 20:12:10,6769.0,1532,25483,False,2021-02-10 23:58:48,"ðŸ˜Ž Today, that's this #Thursday, we will do a ""...","['Thursday', 'Btc', 'wallet', 'security']",Twitter for Android,False
2,Tdlmatias,"London, England","IM Academy : The best #forex, #SelfEducation, ...",2014-11-10 10:50:37,128.0,332,924,False,2021-02-10 23:54:48,"Guys evening, I have read this article about B...",NaN,Twitter Web App,False
3,Crypto is the future,NaN,I will post a lot of buying signals for BTC tr...,2019-09-28 16:48:12,625.0,129,14,False,2021-02-10 23:54:33,$BTC A big chance in a billion! Price: \487264...,"['Bitcoin', 'FX', 'BTC', 'crypto']",dlvr.it,False
4,Alex Kirchmaier ðŸ‡¦ðŸ‡¹ðŸ‡¸ðŸ‡ª #FactsSuperspreader,Europa,Co-founder @RENJERJerky | Forbes 30Under30 | I...,2016-02-03 13:15:55,1249.0,1472,10482,False,2021-02-10 23:54:06,This network is secured by 9 508 nodes as of t...,['BTC'],Twitter Web App,False

In [ ]:
getInfo(uncleaned_df)

           ATTRIBUTE    TYPE   VALUES   UNIQUE     NANS
0          user_name  object  2830476   443139       31
1      user_location  object  2830476    72344  1403546
2   user_description  object  2830476   440375   352680
3       user_created  object  2830476   430262       93
4     user_followers  object  2830476    67584      138
5       user_friends  object  2830476    28043      138
6    user_favourites  object  2830476   118726      138
7      user_verified  object  2830476       20      138
8               date  object  2830476  2208780      138
9               text  object  2830476  2765189      138
10          hashtags  object  2830476   643626    17183
11            source  object  2830476     2152     3754
12        is_retweet  object  2830476        2      441

In [ ]:
print(len(uncleaned_df.text))
print(uncleaned_df.duplicated().sum())

uncleaned_df.drop_duplicates()
print(len(uncleaned_df.text))

uncleaned_df=uncleaned_df.dropna(subset=['text'])
print(len(uncleaned_df.text))

2830476
42
2830476
2830338

In [ ]:
uncleaned_df=uncleaned_df[(uncleaned_df.user_verified==False) | (uncleaned_df.user_verified==True) | (uncleaned_df.user_verified=="True") | (uncleaned_df.user_verified=="False")]
uncleaned_df["user_verified"].replace({"True": True, "False": False}, inplace=True)

print(len(uncleaned_df.text))

#drop is_retweet cause only "nan and false"
#drop hashtags
#drop source
#drop user_favourites
#drop user_friends
uncleaned_df.drop(["is_retweet","hashtags","source"],inplace=True,axis=1)
tweet_data.drop(["user_favourites","user_friends"],inplace=True,axis=1)

print(len(uncleaned_df.text))


uncleaned_df["date"]=[i[:11] for i in uncleaned_df.date ]

2830323
2830323

In [ ]:
getInfo(uncleaned_df)

          ATTRIBUTE    TYPE   VALUES   UNIQUE     NANS
0         user_name  object  2830323   443044       31
1     user_location  object  2830323    72308  1403453
2  user_description  object  2830323   440361   352587
3      user_created  object  2830323   430245        0
4    user_followers  object  2830323    67581        0
5      user_friends  object  2830323    28040        0
6   user_favourites  object  2830323   118711        0
7     user_verified    bool  2830323        2        0
8              date  object  2830323      136        0
9              text  object  2830323  2765183        0

In [ ]:
uncleaned_df.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text
0,DeSota Wilson,"Atlanta, GA","Biz Consultant, real estate, fintech, startups...",2009-04-26 20:05:09,8534.0,7605,4838,False,2021-02-10,Blue Ridge Bank shares halted by NYSE after #b...
1,CryptoND,NaN,ðŸ˜Ž BITCOINLIVE is a Dutch platform aimed at inf...,2019-10-17 20:12:10,6769.0,1532,25483,False,2021-02-10,"ðŸ˜Ž Today, that's this #Thursday, we will do a ""..."
2,Tdlmatias,"London, England","IM Academy : The best #forex, #SelfEducation, ...",2014-11-10 10:50:37,128.0,332,924,False,2021-02-10,"Guys evening, I have read this article about B..."
3,Crypto is the future,NaN,I will post a lot of buying signals for BTC tr...,2019-09-28 16:48:12,625.0,129,14,False,2021-02-10,$BTC A big chance in a billion! Price: \487264...
4,Alex Kirchmaier ðŸ‡¦ðŸ‡¹ðŸ‡¸ðŸ‡ª #FactsSuperspreader,Europa,Co-founder @RENJERJerky | Forbes 30Under30 | I...,2016-02-03 13:15:55,1249.0,1472,10482,False,2021-02-10,This network is secured by 9 508 nodes as of t...

In [ ]:
uncleaned_df.to_csv(r'/content/gdrive/MyDrive/capstone project/modified datasets/CleanedDataset.csv')