In [ ]:
import pandas as pd 
from datetime import datetime
from datetime import timedelta
import os

from tqdm import tnrange, tqdm_notebook, tqdm

In [ ]:
from sklearn import preprocessing
import numpy as np

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
#btc_data = pd.read_csv("/content/gdrive/My Drive/capstone project/datasets/prices/Bitcoin_data.csv") 
btc_data = pd.read_csv("/content/gdrive/My Drive/capstone project/datasets/prices/Bitcoin_prices.csv")

In [ ]:
#Change Date to utc in bitcoin data
btc_data['Date'] = pd.to_datetime(btc_data['Date'], utc = True)

In [ ]:
btc_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-02-05 00:00:00+00:00,36931.546875,38225.906250,36658.761719,38144.308594,38144.308594,58598066402
1,2021-02-06 00:00:00+00:00,38138.386719,40846.546875,38138.386719,39266.011719,39266.011719,71326033653
2,2021-02-07 00:00:00+00:00,39250.191406,39621.835938,37446.152344,38903.441406,38903.441406,65500641143
3,2021-02-08 00:00:00+00:00,38886.828125,46203.929688,38076.324219,46196.464844,46196.464844,101467222687
4,2021-02-09 00:00:00+00:00,46184.992188,48003.722656,45166.960938,46481.105469,46481.105469,91809846886

In [ ]:
dates=[str(i)[:10] for i in list(btc_data.Date)]

In [ ]:
btc_data.Date=dates

In [ ]:

folder = "/content/gdrive/MyDrive/capstone project/modified datasets/CleanedDataset.csv"
  
#print(folder)

#get tweets
tweet_data = pd.read_csv(folder)

In [ ]:
tweet_data.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,user_profession,score,profession_score
0,DeSota Wilson,"Atlanta, GA","Biz Consultant, real estate, fintech, startups...",2009-04-26 20:05:09,8534.0,7605.0,4838.0,False,2021-02-10,Blue Ridge Bank shares halted by NYSE after AT...,-,0.2960,0
1,CryptoND,NaN,ðŸ˜Ž BITCOINLIVE is a Dutch platform aimed at inf...,2019-10-17 20:12:10,6769.0,1532.0,25483.0,False,2021-02-10,"ðŸ˜Ž Today, that's this Thursday, we will do a ""ðŸŽ¬...",-,0.4939,0
2,Tdlmatias,"London, England","IM Academy : The best #forex, #SelfEducation, ...",2014-11-10 10:50:37,128.0,332.0,924.0,False,2021-02-10,"Guys evening, I have read this article about B...",-,0.5719,0
3,Crypto is the future,NaN,I will post a lot of buying signals for BTC tr...,2019-09-28 16:48:12,625.0,129.0,14.0,False,2021-02-10,$BTC A big chance in a billion! Price: \487264...,-,0.3164,0
4,Alex Kirchmaier ðŸ‡¦ðŸ‡¹ðŸ‡¸ðŸ‡ª #FactsSuperspreader,Europa,Co-founder @RENJERJerky | Forbes 30Under30 | I...,2016-02-03 13:15:55,1249.0,1472.0,10482.0,False,2021-02-10,This network is secured by 9 508 nodes as of t...,-,0.4019,0

In [ ]:
tweet_data.user_followers.values

array([8534., 6769.,  128., ...,   82.,   24.,   78.])

In [ ]:
#x â€² = ( x âˆ’ x m i n ) / ( x m a x âˆ’ x m i n )
def normalizeCol(col):
  col=list(col)
  maxx=max(col)
  mini=min(col)
  for i in range(len(col)):
    col[i]=(col[i]-mini)/(maxx-mini)
  return col

In [ ]:
dats=set([i for i in tweet_data.date])
dats=list(dats)
dats.sort()
print(dats[0],dats[-1],len(dats))

2021-02-05  2022-04-16  136

In [ ]:
a=pd.date_range(start="2021-02-05",end="2022-04-16")
len(a)

436

In [ ]:
"""tweet_data.user_followers=normalizeCol(tweet_data.user_followers)
tweet_data.profession_score=normalizeCol(tweet_data.profession_score)"""

In [ ]:
d={}
for i in range(len(tweet_data.user_profession)):
  if tweet_data.date[i] in d:
    d[tweet_data.date[i]][0]+=1
    d[tweet_data.date[i]][1]+=tweet_data.score[i]
  else:
    d[tweet_data.date[i]]=[1,tweet_data.score[i]]

In [ ]:
#taking avg
for i in d:
  d[i][1]=d[i][1]/d[i][0]

In [ ]:
#score is date:[volume,avg score]
score={}
user_followers={}

for i in range(len(tweet_data.user_profession)):
  if tweet_data.date[i] in score:
    score[tweet_data.date[i]][0]+=1 #volume of tweets
    score[tweet_data.date[i]][1]+=tweet_data.score[i] #sum of tweet scores for that day
    
    

  else:
    score[tweet_data.date[i]]=[1,tweet_data.score[i]]
    

#taking avg
for i in score:
  score[i][1]=score[i][1]/score[i][0]  # average tweet score for that day

In [ ]:

user_followers={}

for i in range(len(tweet_data.user_profession)):
  if tweet_data.date[i] in user_followers:
    user_followers[tweet_data.date[i]][0]+=1 #volume of tweets
    user_followers[tweet_data.date[i]][1]+=tweet_data.user_followers[i] #sum of followers for that day
    
    
  else:
    user_followers[tweet_data.date[i]]=[1,tweet_data.score[i]]
    

#taking avg
#for i in score:
 # score[i][1]=score[i][1]/score[i][0]  # average tweet score for that day

In [ ]:

user_prof={}

for i in range(len(tweet_data.user_profession)):
  if tweet_data.date[i] in user_prof:
    user_prof[tweet_data.date[i]][0]+=1 #volume of tweets
    user_prof[tweet_data.date[i]][1]+=tweet_data.profession_score[i] #sum of followers for that day
    
    
  else:
    user_prof[tweet_data.date[i]]=[1,tweet_data.profession_score[i]]

In [ ]:
tweet_dates=[i.strip() for i in list(user_followers.keys())]

vol=[]
avg=[]
user_foll_sum=[]
user_prof_sum=[]


for i in list(score.values()):
  vol.append(i[0])
  avg.append(i[1])

for i in list(user_followers.values()):
  user_foll_sum.append(i[1])


for i in list(user_prof.values()):
  user_prof_sum.append(i[1])

In [ ]:
#user_foll_sum=normalizeCol(user_foll_sum)

In [ ]:
#user_prof_sum=normalizeCol(user_foll_sum)

In [ ]:
tweet_aggregates = pd.DataFrame(
    {
        "Date": tweet_dates,
        "Tweet_volume":vol,
        "Avg_score": avg,
        "sum_followers":user_foll_sum,
        "sum_prof":user_prof_sum,
         
        
    }
    
)

In [ ]:
tweet_aggregates.head()

         Date  Tweet_volume  Avg_score  sum_followers  sum_prof
0  2021-02-10          3526   0.175366   1.950375e+07         0
1  2021-02-09          4350   0.166602   3.187073e+07         0
2  2021-02-08          5647   0.171374   4.810007e+07         0
3  2021-02-07          3030   0.155368   1.203219e+07         0
4  2021-02-06          3278   0.150722   1.657918e+07         0

In [ ]:
final_price_data=pd.merge(btc_data,tweet_aggregates,how="left",on="Date",sort=True)

In [ ]:
final_price_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Tweet_volume,Avg_score,sum_followers,sum_prof
0,2021-02-05,36931.546875,38225.906250,36658.761719,38144.308594,38144.308594,58598066402,1694.0,0.146160,7.683060e+06,0.0
1,2021-02-06,38138.386719,40846.546875,38138.386719,39266.011719,39266.011719,71326033653,3278.0,0.150722,1.657918e+07,0.0
2,2021-02-07,39250.191406,39621.835938,37446.152344,38903.441406,38903.441406,65500641143,3030.0,0.155368,1.203219e+07,0.0
3,2021-02-08,38886.828125,46203.929688,38076.324219,46196.464844,46196.464844,101467222687,5647.0,0.171374,4.810007e+07,0.0
4,2021-02-09,46184.992188,48003.722656,45166.960938,46481.105469,46481.105469,91809846886,4350.0,0.166602,3.187073e+07,0.0

In [ ]:
final_price_data.to_csv(r'/content/gdrive/MyDrive/capstone project/modified datasets/Final_df3.csv')