In [ ]:
import pandas as pd 
from datetime import datetime
from datetime import timedelta
import os

from tqdm import tnrange, tqdm_notebook, tqdm

from sklearn import preprocessing

import numpy as np

In [2]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
def normalizeCol(col):
  col=list(col)
  maxx=max(col)
  mini=min(col)
  for i in range(len(col)):
    col[i]=(col[i]-mini)/(maxx-mini)
  return col

In [ ]:
btc_data = pd.read_csv("/content/gdrive/My Drive/capstone project/modified datasets/Final_df.csv")
next_day_data=pd.read_csv("/content/gdrive/My Drive/capstone project/datasets/prices/Next_Day_Bitcoin_prices.csv")

In [ ]:
next_day_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2021-02-06,38138.386719,40846.546875,38138.386719,39266.011719,39266.011719,71326033653
1,2021-02-07,39250.191406,39621.835938,37446.152344,38903.441406,38903.441406,65500641143
2,2021-02-08,38886.828125,46203.929688,38076.324219,46196.464844,46196.464844,101467222687
3,2021-02-09,46184.992188,48003.722656,45166.960938,46481.105469,46481.105469,91809846886
4,2021-02-10,46469.761719,47145.566406,43881.152344,44918.183594,44918.183594,87301089896

In [ ]:
next_day_data.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
431,2022-04-13,40123.570312,41430.054688,39712.746094,41166.730469,41166.730469,27691105228
432,2022-04-14,41160.218750,41451.480469,39695.746094,39935.515625,39935.515625,24342001973
433,2022-04-15,39939.402344,40617.722656,39866.832031,40553.464844,40553.464844,21756855753
434,2022-04-16,40552.316406,40633.679688,40078.425781,40424.484375,40424.484375,16833150693
435,2022-04-17,40417.777344,40570.726562,39620.894531,39716.953125,39716.953125,19087633042

df=btc_data

In [ ]:
df=btc_data
df["next"]=next_day_data["Open"]

In [ ]:
df

,Unnamed: 0,Date,Open,High,Low,Close,Adj Close,Volume,Tweet_volume,Avg_score,Avg_score_norm,Tweet_volume_norm,next
0,0,2021-02-05,36931.546875,38225.906250,36658.761719,38144.308594,38144.308594,58598066402,1694.0,0.000025,0.043308,0.022462,38138.386719
1,1,2021-02-06,38138.386719,40846.546875,38138.386719,39266.011719,39266.011719,71326033653,3278.0,0.000021,0.032583,0.044547,39250.191406
2,2,2021-02-07,39250.191406,39621.835938,37446.152344,38903.441406,38903.441406,65500641143,3030.0,0.000009,0.000000,0.041089,38886.828125
3,3,2021-02-08,38886.828125,46203.929688,38076.324219,46196.464844,46196.464844,101467222687,5647.0,0.000055,0.129953,0.077577,46184.992188
4,4,2021-02-09,46184.992188,48003.722656,45166.960938,46481.105469,46481.105469,91809846886,4350.0,0.000057,0.136786,0.059494,46469.761719
...,...,...,...,...,...,...,...,...,...,...,...,...,...
431,431,2022-04-12,39533.714844,40617.585938,39388.328125,40127.183594,40127.183594,30991500854,NaN,NaN,NaN,NaN,40123.570312
432,432,2022-04-13,40123.570312,41430.054688,39712.746094,41166.730469,41166.730469,27691105228,18397.0,0.000058,0.137809,0.255347,41160.218750
433,433,2022-04-14,41160.218750,41451.480469,39695.746094,39935.515625,39935.515625,24342001973,27676.0,0.000063,0.153244,0.384722,39939.402344
434,434,2022-04-15,39939.402344,40617.722656,39866.832031,40553.464844,40553.464844,21756855753,40576.0,0.000075,0.185499,0.564583,40552.316406
435,435,2022-04-16,40552.316406,40633.679688,40078.425781,40424.484375,40424.484375,16833150693,44531.0,0.000050,0.116421,0.619726,40417.777344

In [ ]:
df=df.drop(["Unnamed: 0","High","Low","Close","Adj Close","Volume","Tweet_volume","Avg_score"],axis=1)

In [ ]:
df.Open=normalizeCol(df.Open)
df.next=normalizeCol(df.next)

In [ ]:
#df=df.set_index('Date')

In [ ]:
df

           Date      Open  Avg_score_norm  Tweet_volume_norm      next
0    2021-02-05  0.188996        0.043308           0.022462  0.220963
1    2021-02-06  0.220963        0.032583           0.044547  0.250412
2    2021-02-07  0.250412        0.000000           0.041089  0.240787
3    2021-02-08  0.240787        0.129953           0.077577  0.434098
4    2021-02-09  0.434098        0.136786           0.059494  0.441641
..          ...       ...             ...                ...       ...
431  2022-04-12  0.257922             NaN                NaN  0.273545
432  2022-04-13  0.273545        0.137809           0.255347  0.301004
433  2022-04-14  0.301004        0.153244           0.384722  0.268667
434  2022-04-15  0.268667        0.185499           0.564583  0.284902
435  2022-04-16  0.284902        0.116421           0.619726  0.281338

[436 rows x 5 columns]

In [ ]:
np.isnan(df["Avg_score_norm"]).count()

436

In [ ]:
df.to_csv('/content/gdrive/My Drive/capstone project/datasets/prices/Full_trial_data.csv',index=False)