In [ ]:
! pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.84-py2.py3-none-any.whl (29 kB)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.4.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.2 MB/s
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.9.24)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Installing collected packages: requests, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
Successfully installed requests-2.28.1 yfinance-0.1.84

In [ ]:
# Raw Package
import numpy as np
import pandas as pd

#Data Source
import yfinance as yf
import datetime
import time

In [ ]:
def get_data(symbol, interval, start, end):
    data = yf.download(tickers=symbol, start=start, end=end, interval=interval)
    return data

In [ ]:
def get_data(symbol, interval, start, end):
    data = yf.download(tickers=symbol, start=start, end=end, interval=interval)
    return data

symbol = "BTC-USD"
interval = "1d"
start = "2021-02-05"
end = "2022-04-18"
data = get_data(symbol, interval, start, end)

[*********************100%***********************]  1 of 1 completed

In [ ]:
data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-02-06,38138.386719,40846.546875,38138.386719,39266.011719,39266.011719,71326033653
2021-02-07,39250.191406,39621.835938,37446.152344,38903.441406,38903.441406,65500641143
2021-02-08,38886.828125,46203.929688,38076.324219,46196.464844,46196.464844,101467222687
2021-02-09,46184.992188,48003.722656,45166.960938,46481.105469,46481.105469,91809846886
2021-02-10,46469.761719,47145.566406,43881.152344,44918.183594,44918.183594,87301089896
...,...,...,...,...,...,...
2022-04-13,40123.570312,41430.054688,39712.746094,41166.730469,41166.730469,27691105228
2022-04-14,41160.218750,41451.480469,39695.746094,39935.515625,39935.515625,24342001973
2022-04-15,39939.402344,40617.722656,39866.832031,40553.464844,40553.464844,21756855753
2022-04-16,40552.316406,40633.679688,40078.425781,40424.484375,40424.484375,16833150693
2022-04-17,40417.777344,40570.726562,39620.894531,39716.953125,39716.953125,19087633042

In [ ]:
data.drop("Adj Close",axis=1)

,Open,High,Low,Close,Volume
Date,,,,,
2021-02-06,38138.386719,40846.546875,38138.386719,39266.011719,71326033653
2021-02-07,39250.191406,39621.835938,37446.152344,38903.441406,65500641143
2021-02-08,38886.828125,46203.929688,38076.324219,46196.464844,101467222687
2021-02-09,46184.992188,48003.722656,45166.960938,46481.105469,91809846886
2021-02-10,46469.761719,47145.566406,43881.152344,44918.183594,87301089896
...,...,...,...,...,...
2022-04-13,40123.570312,41430.054688,39712.746094,41166.730469,27691105228
2022-04-14,41160.218750,41451.480469,39695.746094,39935.515625,24342001973
2022-04-15,39939.402344,40617.722656,39866.832031,40553.464844,21756855753
2022-04-16,40552.316406,40633.679688,40078.425781,40424.484375,16833150693
2022-04-17,40417.777344,40570.726562,39620.894531,39716.953125,19087633042

In [ ]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
#/content/gdrive/MyDrive/z0mgs_with_MW_LMC_220517_ww_w_gal_magnetar.npy

In [ ]:
results=data.drop()
data.iloc[:-1 , :].to_csv('/content/gdrive/My Drive/capstone project/datasets/prices/Bitcoin_prices.csv',index=False)

In [ ]:
data.iloc[1: , :]["Open"].to_csv('/content/gdrive/My Drive/capstone project/datasets/prices/Next_Day_Bitcoin_prices.csv',,index=False)

In [ ]:
"""import pandas as pd
# List of Tuples
empoyees = [('Jack',    34, 'Sydney',   5) ,
            ('Riti',    31, 'Delhi' ,   7) ,
            ('Aadi',    16, 'London',   11) ,
            ('Mark',    41, 'Delhi' ,   12)]
# Create a DataFrame object
df = pd.DataFrame(  empoyees, 
                    columns=['Name', 'Age', 'City', 'Experience'])
print("Contents of the Dataframe : ")
print(df)
# Drop first row 
# by selecting all rows from first row onwards

print("Modified Dataframe : ",df.iloc[1:-1 , :])"""